### ISSUE TITLE
Spline post-processing after finite difference

### ISSUE THREAD

**Issue by scaomath** [NBoulle/pde-learning#1]
Nice paper. Can you confirm that,  in the data generation for the Poisson problem $-\Delta u = f$ for $u\in H^1_0$, the finite difference solution is actually post-processed by this line of code?

https://github.com/NBoulle/pde-learning/blob/61f9838d11c4620771fbaa604325872443b29e66/data/solve_gwf.m#L16

**Comment by NBoulle** [comment]
Yes, this is a code from https://github.com/neuraloperator/neuraloperator/tree/master/data_generation/darcy.
